# Generated by Django 2.2b1 on 2019-03-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatorgrouper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_name',
            field=models.CharField(default='Group Project', max_length=30),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
