""" These are global constants """

# default
ALGORITHM_ROUND_ROBIN = "rrobin"
ALGORITHM_RANDOM = "random"
ALGORITHM_GRAPH = "graph"
DEFAULT_METHOD = ALGORITHM_RANDOM
DEFAULT_ABSENT = ""
DEFAULT_PREFERENCES = None
DEFAULT_PREFERENCES_WEIGHT = 1.1
DEFAULT_PREFERENCES_WEIGHT_MATCH = 1.3
DEFAULT_OBJECTIVE_WEIGHTS = None
DEFAULT_OBJECTIVE_MEASURES = None

# assertion
NONE = ""

# recognizer
EMPTY_STRING = ""
ERROR = "error:"
