""" These are global constants """

# default
ALGORITHM_ROUND_ROBIN = "rrobin"
ALGORITHM_RANDOM = "random"
ALGORITHM_GRAPH = "graph"
DEFAULT_METHOD = ALGORITHM_RANDOM
DEFAULT_GRPSIZE = 3
DEFAULT_NUMGRP = 3
DEFAULT_ABSENT = ""
DEFAULT_PREFERENCES = None
DEFAULT_PREFERENCES_WEIGHT = 1.1
DEFAULT_PREFERENCES_WEIGHT_MATCH = 1.3
DEFAULT_OBJECTIVE_WEIGHTS = None
DEFAULT_OBJECTIVE_MEASURES = None

# assertion
NONE = ""

# recognizer
EMPTY_STRING = ""
ERROR = "error:"

# Define configuration variables

DEFAULT_GROUP_SIZE = 2
WORKBOOK = "GatorGrouper (Responses)"
WORKBOOK_CSV = WORKBOOK.replace(" ", "_") + ".csv"
