# Generated by Django 2.1.7 on 2019-02-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grouped_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=40)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatorgrouper.Assignments')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('email', models.EmailField(max_length=200)),
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Class',
            fields=[
                ('semester', models.CharField(max_length=50)),
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=10)),
                ('class_number', models.CharField(max_length=10)),
                ('class_section', models.CharField(max_length=10)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatorgrouper.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatorgrouper.Semester_Class')),
            ],
        ),
        migrations.AddField(
            model_name='grouped_students',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatorgrouper.Students'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatorgrouper.Semester_Class'),
        ),
    ]
